CREATE TABLE K911_dogs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    pet_name TEXT NOT NULL,
    birthday DATE,
    medication TEXT,
    about TEXT,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP
);