BEGIN;

TRUNCATE
  K911_foods,
  K911_medicine,
  K911_plants,
  K911_users,
  K911_dogs
  RESTART IDENTITY CASCADE;

INSERT INTO K911_users (user_name, full_name, pet_name, password)
VALUES
  ('DoggoGuy', 'Jake McPupper', 'Pancake', 'Jake-password'),
  ('PupLuv', 'Kelly Cavalier', 'Bo', 'Kelly-password'),
  ('Lexlor', 'Alex Retriever', 'Angela Basset-hound', 'Alex-password'),
  ('wippy', 'Doug Dogglas', 'Scoobie', 'Doug-password');

INSERT INTO K911_dogs (owner_id, pet_name, birthday, medication, about)
VALUES
  (1, 'Pancake', '2010-08-10', 'Flea and Tick prevention', 'Walks, the dog park, tennis balls' ),
  (2, 'Bo', '2015-10-01', 'Flea and Tick prevention, Prozac', 'Parks, bones'),
  (3, 'Angela Basset-hound', '2018-02-18', 'Trifexis, Cytopoint Shots', 'the bed, trail runs, and her stuffed toy dinosaur'),
  (4, 'Scoobie', '2019-11-22', 'Flea and Tick prevention', 'Walks, fetch, tennis balls');

INSERT INTO K911_foods (name, toxicity, toxic, toxic_principles, symptom)
VALUES
  ('Alcohol', 'Toxic', true, 'Unknown',
    'Vomiting, diarrhea, decreased coordination, central nervous system depression, difficulty breathing, tremors, abnormal blood acidity, coma and death.'),
  ('Grapes', 'Toxic', true, 'Unknown',
    'Kidney failure.'),
  ('Orange', 'Toxic', true, 'Psoralens and essential oils',
    'Depression, diarrhea and vomiting. The oils from the skin, peels, and leaves are the primary problem.'),
  ('Lemon', 'Toxic', true, 'Psoralens and essential oils',
    'Depression, diarrhea and vomiting. The oils from the skin, peels, and leaves are the primary problem.'),
  ('Lime', 'Toxic', true, 'Psoralens and essential oils',
    'Depression, diarrhea and vomiting. The oils from the skin, peels, and leaves are the primary problem.'),
  ('Raisins', 'Toxic', true, 'N-propyl disulfide',
    'Vomiting, breakdown of red blood cells (hemolytic anemia, Heinz body anemia), blood in urine, weakness, high heart rate, panting.'),
  ('Garlic', 'Toxic', true, 'N-propyl disulfide',
    'Vomiting, breakdown of red blood cells (hemolytic anemia, Heinz body anemia), blood in urine, weakness, high heart rate, panting.'),
  ('Chive', 'Toxic', true, 'N-propyl disulfide',
    'Vomiting, breakdown of red blood cells (hemolytic anemia, Heinz body anemia), blood in urine, weakness, high heart rate, panting.'),
  ('Oregano', 'Toxic', true, 'Gastrointestinal irritants',
    'Mild vomiting and diarrhea.'),
  ('Leek', 'Toxic', true, 'N-propyl disulfide',
    'Vomiting, breakdown of red blood cells (hemolytic anemia, Heinz body anemia), blood in urine, weakness, high heart rate, panting.'),
  ('Rhubarb', 'Toxic', true, 'Soluble calcium oxalates',
    'Kidney failure, tremors, salivation.'),
  ('Lemon Grass', 'Toxic', true, 'Essential oils, cyanogenic glycosides',
    'Stomach upset.'),
  ('Hops', 'Toxic', true, 'Unknown',
    'Panting, high body temperature, seizures, death.'),
  ('Fruit Pits and Seeds', 'Toxic', true, 'Various',
    'Many fruit pits and seeds contain cyanide or arsenic. Apples, cherries, apricots, plums, and peaches are a few examples of fruits with toxic seeds and stones. Dogs can also easily choke on them.'),
  ('Yeast Dough', 'Toxic', true, 'Unknown',
    'Can cause a buildup of gas released from the dough, resulting in bloated stomach, which can potentially twist and become life-threatening.'),
  ('Candy', 'Toxic', true, 'Various',
    'Candy can contain many different toxins for dogs. Common issues are sweeteners, artificial sweeteners, chocolate, and alcohols.'),
  ('Macademia Nut', 'Toxic', true, 'Unknown',
    'Depression, weakness (especially of rear limbs), vomiting, tremors.'),
  ('Chocolate', 'Toxic', true, 'Methylxanthines',
    'Vomiting and diarrhea, panting, excessive thirst and urination, hyperactivity, abnormal heart rhythm, tremors, seizures, death.'),
  ('Coffee', 'Toxic', true, 'Methylxanthines',
    'Vomiting and diarrhea, panting, excessive thirst and urination, hyperactivity, abnormal heart rhythm, tremors, seizures, death.'),
  ('Acorn Squash', 'Non-Toxic', false, '',
    ''),
  ('Banana', 'Non-Toxic', false, '',
    ''),
  ('Carob', 'Non-Toxic', false, '',
    ''),
  ('Carrot', 'Non-Toxic', false, '',
    ''),
  ('Cashews', 'Non-Toxic', false, '',
    ''),
  ('Cilantro', 'Non-Toxic', false, '',
    ''),
  ('Cinnamon', 'Non-Toxic', false, '',
    ''),
  ('Cucumber', 'Non-Toxic', false, '',
    ''),
  ('Eggs', 'Non-Toxic', false, '',
    ''),
  ('Fennel', 'Non-Toxic', false, '',
    ''),
  ('Honeydew Melon', 'Non-Toxic', false, '',
    ''),
  ('Honey', 'Non-Toxic', false, '',
    ''),
  ('Green Beans', 'Non-Toxic', false, '',
    ''),
  ('Sweet Potato', 'Non-Toxic', false, '',
    ''),
  ('Strawberry', 'Non-Toxic', false, '',
    ''),
  ('Blueberry', 'Non-Toxic', false, '',
    ''),
  ('Watermelon', 'Non-Toxic', false, 'Watermelon flesh is safe, but be careful of the seeds.',
    ''),
  ('Peanut Butter', 'Non-Toxic', false, 'Look for unsalted varieties.',
    ''),
  ('Pitaya, Dragonfruit', 'Non-Toxic', false, '',
    ''),
  ('Pumpkin', 'Non-Toxic', false, '',
    ''),
  ('Quinoa', 'Non-Toxic', false, '',
    ''),
  ('Zucchini', 'Non-Toxic', false, '',
    ''),
  ('Broccoli', 'Non-Toxic', false, '',
    ''),
  ('Kale', 'Non-Toxic', false, '',
    '')
  ;



INSERT INTO K911_plants (name, toxicity, toxic, toxic_principles, symptom)
VALUES
('Aloe vera', 'Toxic', true, 'Saponins, anthraquinones',
  'Vomiting, lethargy, diarrhea.'),
('Amaryllis', 'Toxic', true, 'Lycorine and others',
  'Vomiting (not horses), depression, diarrhea, abdominal pain, hypersalivation, anorexia, tremors.'),
('American Holly', 'Toxic', true, 'Saponins',
  'Vomiting, diarrhea and depression.'),
('Angelica Tree', 'Toxic', true, 'Araliin',
  'Skin and oral irritation, hypersalivation, vomiting, diarrhea'),
('Azalea', 'Toxic', true, 'Grayantoxin',
  'Vomiting, diarrhea, hypersalivation, weakness, coma, hypotension, CNS depression, cardiovascular collapse and death. Even minor consumption can cause serious problems.'),
('Bay Laurel', 'Toxic', true, 'Eugenol, and other essential oils',
  'Vomiting and diarrhea, Large ingestion of whole leaves can cause obstruction'),
('Begonia', 'Toxic', true, 'Soluble calcium oxalates',
  'Vomiting, salivation. Most toxic part is underground.'),
('Bird of Paradise', 'Toxic', true, 'GI irritants, possibly hydrocyanic acid',
  'Oral irritation, intense burning and irritation of mouth, tongue and lips, excessive drooling, vomiting, diarrhea, difficulty swallowing and incoordination is possible.'),
('Black Nightshade', 'Toxic', true, 'Solanine, saponins, atropine like substances',
  'Hypersalivation, inappetence, severe gastrointestinal upset, diarrhea, drowsiness, CNS depression, confusion, behavioral change, weakness, dilated pupils, slow heart rate.'),
('Butterfly Iris', 'Toxic', true, 'Pentacylic terpenoids',
  'Salivation, vomiting, drooling,lethargy, diarrhea. Highest concentration in rhizomes.'),
('Calla Lily', 'Toxic', true, 'Insoluble calcium oxalates',
  'Oral irritation, intense burning and irritation of mouth, tongue and lips, excessive drooling, vomiting, difficulty swallowing.'),
('Christmas Rose, Lenten Rose', 'Toxic', true, 'Cardiac glycosides, saponins, protoanemonin',
  'Drooling, abdominal pain, diarrhea, colic, depression.'),
('Clematis', 'Toxic', true, 'Irritant glycoside',
  'Salivation, vomiting, diarrhea.'),
('Corn Plant, Cornstalk Plant', 'Toxic', true, 'Saponins',
  'Vomiting (occasionally with blood), depression, anorexia, hypersalivation.'),
('Cyclamen', 'Toxic', true, 'Terpenoid saponins',
  'Salivation, vomiting, diarrhea. Following large ingestions of tubers: heart rhythm abnormalities, seizures, death.'),
('Dahlia', 'Toxic', true, 'Unknown',
  'Mild gastrointestinal signs, mild dermatitis.'),
('Daffodil, Jonquil', 'Toxic', true, 'Lycorine and other alkaloids',
  'Vomiting, salvation, diarrhea; large ingestions cause convulsions, low blood pressure, tremors and cardiac arrhythmias. Bulbs are the most poisonous part.'),
('Dumbcane', 'Toxic', true, 'Insoluble calcium oxalates, proteolytic enzyme',
  'Oral irritation, intense burning and irritation of mouth , tongue and lips, excessive drooling, vomiting, difficulty swallowing.'),
('Elephant Ears', 'Toxic', true, 'Insoluble calcium oxalates',
  'Oral irritation, pain and swelling of mouth, tongue and lips, excessive drooling, vomiting, difficulty swallowing'),
('Flamingo Flower', 'Toxic', true, 'Insoluble calcium oxalates',
  'Oral irritation, pain and swelling of mouth, tongue and lips, excessive drooling, vomiting, difficulty swallowing'),
('Fire Lily', 'Toxic', true, 'Lycorine and other alkaloids',
  'Vomiting, salvation, diarrhea; large ingestions cause convulsions, low blood pressure, tremors and cardiac arrhythmias. Bulbs are the most poisonous part.'),
('Fox Glove', 'Toxic', true, 'Cardiac glycosides',
  'Cardiac arrhythmias, vomiting, diarrhea, weakness, cardiac failure, death.'),
('Gardenia', 'Toxic', true, 'Genioposide, gardenoside',
  'Mild vomiting and/or diarrhea, hives.'),
('Gladiola', 'Toxic', true, 'Unknown',
  'Salivation, vomiting, drooling,lethargy, diarrhea.'),
('Hosta', 'Toxic', true, 'Saponins',
  'Vomiting, diarrhea, depression.'),
('Jade Plant', 'Toxic', true, 'Unknown',
  'Vomiting, depression, incoordination'),
('Kalanchoe', 'Toxic', true, 'Bufodienolides',
  'Vomiting, diarrhea, abnormal heart rhythm (rare).'),
('Marjoram', 'Toxic', true, 'Gastrointestinal irritants',
  'Vomiting and diarrhea.'),
('Morning Glory', 'Toxic', true, 'Indole alkaloids (Lysergic acid, lysergamide, elymoclavine and chanoclavine)',
  'Vomiting.'),
('Moss Rose', 'Toxic', true, 'Soluble calcium oxalates',
  'Kidney failure (rare), tremors.'),
('Nandina', 'Toxic', true, 'Cyanogenic glycosides',
  'Weakness, incoordination, seizures, coma, respiratory failure, death (rare).'),
('Oleander', 'Toxic', true, 'Cardiac glycosides',
  'Drooling, abdominal pain, diarrhea, colic, depression, death'),
('Peony', 'Toxic', true, 'Paeonol',
  'Vomiting, diarrhea, depression'),
('Portulaca', 'Toxic', true, 'Soluble calcium oxalates',
  'Kidney failure (rare), tremors.'),
('Poinsettia', 'Toxic', true, 'Irritant sap',
  'Irritating to the mouth and stomach, some vomiting.'),
('Rhododendron', 'Extremely Toxic', true, 'Grayantoxin',
  'Vomiting, diarrhea, hypersalivation, weakness, coma, hypotension, CNS depression, cardiovascular collapse and death. Even minor consumption can cause serious problems.'),
('Sago Palm', 'Toxic', true, 'Cycasin',
  'Vomiting, melena, icterus, increased thirst, hemorrhagic gastroenteritis, bruising, coagulopathy, liver damage, liver failure, death.'),
('Sweet Pea', 'Toxic', true, 'Aminoproprionitrite',
  'Weakness, lethargy, pacing, head pressing, tremors, seizures and possibly death.'),
('Tobacco', 'Toxic', true, 'Nicotine',
  'Hyperexcitability then depression, vomiting, incoordination, paralysis, death is possible.'),
('Tulip', 'Toxic', true, 'Tulipalin A and B',
  'Vomiting, depression, diarrhea, hypersalivation. Highest concentration of toxin in bulb.'),
('Vinca', 'Toxic', true, 'Vinca Alkaloids',
  'Vomiting, diarrhea, low blood pressure, depression, tremors, seizures, coma, death.'),
('Wisteria', 'Toxic', true, 'Lectin, wisterin glycoside',
  'Vomiting (sometimes with blood), diarrhea, depression.'),
('Yucca', 'Toxic', true, 'Saponins',
  'Vomiting.'),
('African Violet', 'Non-Toxic', false, '',
  ''),
('Bamboo', 'Non-Toxic', false, '',
  ''),
('Blue Bottle', 'Non-Toxic', false, '',
  ''),
('Boston Fern', 'Non-Toxic', false, '',
  ''),
('Burro Tail', 'Non-Toxic', false, '',
  ''),
('Camellia', 'Non-Toxic', false, '',
  ''),
('Corn Flower', 'Non-Toxic', false, '',
  ''),
('Day Lillies', 'Non-Toxic', false, '',
  ''),
('Duffii Fern', 'Non-Toxic', false, '',
  ''),
('Dwarf Palm', 'Non-Toxic', false, '',
  ''),
('Easter Lily', 'Non-Toxic', false, '',
  ''),
('Gerber Daisy', 'Non-Toxic', false, '',
  ''),
('Ghost Plant', 'Non-Toxic', false, '',
  ''),
('Grape Hyacinth', 'Non-Toxic', false, '',
  ''),
('Hens and Chickens', 'Non-Toxic', false, '',
  ''),
('Hibiscus', 'Non-Toxic', false, '',
  ''),
('Ice Plant', 'Non-Toxic', false, '',
  ''),
('Impatience', 'Non-Toxic', false, '',
  ''),
('Irish Moss', 'Non-Toxic', false, '',
  ''),
('Jasmine', 'Non-Toxic', false, '',
  ''),
('Lemon Balm', 'Non-Toxic', false, '',
  ''),
('Leopard Lily', 'Non-Toxic', false, '',
  ''),
('Mariposa Lily', 'Non-Toxic', false, '',
  ''),
('Nasturtium', 'Non-Toxic', false, '',
  ''),
('Orange Star', 'Non-Toxic', false, '',
  ''),
('Painted Lady', 'Non-Toxic', false, '',
  ''),
('Pampas Grass', 'Non-Toxic', false, '',
  ''),
('Peperomia', 'Non-Toxic', false, '',
  ''),
('Petunia', 'Non-Toxic', false, '',
  ''),
('Phalaenopsis Orchid', 'Non-Toxic', false, '',
  ''),
('Pink Splash', 'Non-Toxic', false, '',
  ''),
('Queens Spiderwort', 'Non-Toxic', false, '',
  ''),
('Reed Palm', 'Non-Toxic', false, '',
  ''),
('Sage', 'Non-Toxic', false, '',
  ''),
('Scarlet Orchid', 'Non-Toxic', false, '',
  ''),
('Shrimp Cactus', 'Non-Toxic', false, '',
  ''),
('Silver Bell', 'Non-Toxic', false, '',
  ''),
('Thea Japonica', 'Non-Toxic', false, '',
  ''),
('Tiger Lily', 'Non-Toxic', false, '',
  ''),
('Toad Spotted Cactus', 'Non-Toxic', false, '',
  ''),
('Umbrella Plant', 'Non-Toxic', false, '',
  ''),
('Urbinia Agavoides', 'Non-Toxic', false, '',
  ''),
('Velvet Plant', 'Non-Toxic', false, '',
  ''),
('Venus Fly Trap', 'Non-Toxic', false, '',
  ''),
('Water Hyacinth', 'Non-Toxic', false, '',
  ''),
('Wild Lantana', 'Non-Toxic', false, '',
  ''),
('Wool Flower', 'Non-Toxic', false, '',
  ''),
('Yorba Linda', 'Non-Toxic', false, '',
  ''),
('Zinnia', 'Non-Toxic', false, '',
  '')
;

INSERT INTO K911_medicine (name, toxicity, toxic, brands, symptom)
VALUES
  ('Acetaminophen', 'Toxic', true, 'Tylenol, Ofirmev, FeverAll, Tactinal',
    'Potentially deadly. Jaundice, labored breathing, vomiting, hypothermia, swollen face or neck, coma.'),
  ('Diphenhydramine', 'Non-Toxic', false, 'Benadryl, Nytol, Banophen',
    ''),
  ('Cough Drops', 'Toxic', true, 'Various',
    'Common ingredients, like Xylitol, can cause hypoglycemia and possible liver injury depending on the amount present in the cough drops and how many were ingested.  Benzocaine most often causes gastrointestinal upset; however, it is also metabolized into compounds which are capable of causing methemoglobinemia at high doses.'),
  ('Famotidine', 'Non-Toxic', false, 'Pepcid AC',
    ''),
  ('5-fluorouracil', 'EXTREMELY Toxic', true, 'Efudex',
    'Severe vomiting and diarrhea (both with blood); CNS signs, such as seizures, tremors, and opisthotonus; and cardiac arrest.'),
  ('Loperamide', 'Non-Toxic', false, 'Imodium',
    'While generally safe, some breeds related to Collies may have adverse reactions to Imodium. Do not give this medicine to Collies, Shelties, Australian Shepherds and Long-haired Whippets.'),
  ('Antibiotic Ointments & Other Topical Creams', 'Non-Toxic', false, 'Neosporin, Hydrocortisone',
    '')
;

COMMIT;
